schema_version = "1.0.0"

id = "trajectory_anim"
version = "1.1.0"
name = "Trajectory Anim"
tagline = "Animate quickly by drawing trajectory line"
maintainer = "Trisnox"
type = "add-on"

website = "https://trisnox.github.io/trajectory-anim"

tags = ["Animation"]

blender_version_min = "4.3.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2025 Trisnox",
  "2024 zeffii (aka Dealga McArdle)",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/backup/",
  ".gitignore",
  "README.md"
]